name: dpa
description: DPA app
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  firebase_core: ^0.4.0+1
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.4
  google_sign_in: ^4.0.7
  flutter_facebook_login: ^2.0.1
  camera: ^0.5.4+1
  path_provider: ^1.3.0
  path: ^1.6.2
  flutter_redux: ^0.5.3
  flutter_svg: ^0.14.1
  firebase_storage: ^3.0.6
  uuid: ^2.0.2
  cloud_firestore: ^0.13.0+1
  flutter_rating_bar: ^3.0.0
  cached_network_image: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - lang/en.json
    - assets/

  uses-material-design: true

  fonts:
    - family:  MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf
          weight: 900

    - family: PrimerPrint
      fonts:
        - asset: fonts/PrimerPrint.ttf
        - asset: fonts/PrimerPrintBold.ttf

    - family: Aaargh
      fonts:
        - asset: fonts/Aaargh.ttf
