name: dpa
description: DPA app
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  firebase_core: ^0.4.3+3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  camera: ^0.5.7+3
  path_provider: ^1.6.0
  path: ^1.6.4
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  flutter_svg: ^0.17.1
  firebase_storage: ^3.1.1
  uuid: ^2.0.4
  cloud_firestore: ^0.13.2+1
  flutter_rating_bar: ^3.0.1+1
  cached_network_image: ^2.0.0
  charts_flutter: ^0.8.1
  stack_trace: ^1.9.3
  rx: ^0.0.4
  rxdart: ^0.23.1
  flutter_rx_stream_builder: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - lang/en.json
    - assets/

  uses-material-design: true

  fonts:
    - family:  MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf
          weight: 900

    - family: PrimerPrint
      fonts:
        - asset: fonts/PrimerPrint.ttf
        - asset: fonts/PrimerPrintBold.ttf

    - family: Aaargh
      fonts:
        - asset: fonts/Aaargh.ttf
